package ixigo.example.apple.ixigohack.extras;

public interface AppConstants {

    int TYPE_RECYCLER_VIEW_NORMAL = 0;
    int TYPE_RECYCLER_VIEW_LOADING = 1;
    int TYPE_RECYCLER_VIEW_HEADER = 2;
    int TYPE_RECYCLER_VIEW_FOOTER = 3;

    public interface ACTIVITY_OPEN_REQUEST_CODES {
        int ACTIVITY_LOCATION_SELECTION_ORIGIN = 1;
        int ACTIVITY_LOCATION_SELECTION_DESTINATION = 2;
        int ACTIVITY_GOOGLE_LOGIN = 3;
    }

    public interface INTENT_EXTRAS {
        String EXTRA_LOCATION_AUTOCOMPLETE = "EXTRA_LOCATION_AUTOCOMPLETE";
        String EXTRA_PLACE_ID_PLANNER = "EXTRA_PLACE_ID_PLANNER";
        String EXTRA_PLACE_NAME_PLANNER = "EXTRA_PLACE_NAME_PLANNER";
        String EXTRA_FRAGMENT_POSITION = "EXTRA_FRAGMENT_POSITION";
        String EXTRA_DAYS_PLANNER = "EXTRA_DAYS_PLANNER";
        String EXTRA_ANDROID_DEVICE_ID = "EXTRA_ANDROID_DEVICE_ID";
    }

    public interface FRAGMENT_EXTRAS {
        String EXTRA_FRAGMENT_POSITION = "EXTRA_FRAGMENT_POSITION";
        String EXTRA_FRAGMENT_DIALOG_TITLE = "EXTRA_FRAGMENT_DIALOG_TITLE";
        String EXTRA_FRAGMENT_PLACE_PICKER_RESPONSE = "EXTRA_FRAGMENT_PLACE_PICKER_RESPONSE";
        String EXTRA_FRAGMENT_DEVICE_ID = "EXTRA_FRAGMENT_DEVICE_ID";
        String EXTRA_FRAGMENT_PLACE_ID = "EXTRA_FRAGMENT_PLACE_ID";
    }

    public interface FIREBASE_CONSTANTS {
        String FIREBASE_ROOT_NODE = "plans";
    }

    public interface BRANCH {
        String BRANCH_PLACE_ID = "BRANCH_PLACE_ID";
        String BRANCH_PLACE_NAME = "BRANCH_PLACE_NAME";
        String BRANCH_ANDROID_ID = "BRANCH_ANDROID_ID";
        String BRANCH_DAYS = "BRANCH_DAYS";
    }
}
